services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        working_dir: /app
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        command: tail -f /dev/null
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: pulling_data_api
            MYSQL_USER: pulling_data
            MYSQL_PASSWORD: zQtmgVdRE2441
            MYSQL_ROOT_PASSWORD: root
